/* ═══════════════════════════════════════════════════════════════════
   CLIDecoder — Offline Knowledge Base
   No API key needed. All explanations are local.
   ═══════════════════════════════════════════════════════════════════ */

/* Operators that are always classified as "pipe" type */
const PIPE_OPS = new Set(['|','||','&&',';','&','>','>>','<','<<','2>&1','2>/dev/null','&>','1>','1>>']);

/* Token types allowed */
const VALID_TYPES = new Set(['cmd','sub','flag','arg','val','pipe','other']);

/* ── MAIN KNOWLEDGE BASE ──────────────────────────────────────────── */
const KB = {

  /* ── LINUX / UNIX ─────────────────────────────────────────────── */
  ls:   { desc:'List directory contents', flags:{ '-l':'Long listing with permissions and sizes','-a':'Include hidden (dot) files','-h':'Human-readable sizes (KB, MB)','-r':'Reverse sort order','-t':'Sort by modification time','-R':'Recursively list subdirectories','-S':'Sort by file size largest first','-d':'List directory itself not contents','-1':'One file per line','--color':'Colorize output','-lah':'Long format, all files, human-readable','-la':'Long format including hidden files' }},
  grep: { desc:'Search for patterns in text', flags:{ '-r':'Search recursively in directories','-n':'Show line numbers','-i':'Case-insensitive search','-v':'Invert — show non-matching lines','-l':'List only filenames with matches','-c':'Count matching lines','-E':'Extended regex (ERE)','-P':'Perl-compatible regex','-A':'N lines of context after match','-B':'N lines of context before match','-C':'N lines of context around match','-w':'Match whole words only','-o':'Print only matched parts','-q':'Quiet — exit code only','--include':'Search files matching glob pattern','--exclude':'Skip files matching glob pattern','-F':'Fixed string (not regex)','-m':'Stop after N matches','-H':'Print filename with each match' }},
  find: { desc:'Search files and directories recursively', flags:{ '-name':'Match by filename (wildcards ok)','-type':'Filter by type: f=file d=dir l=symlink','-size':'Match by size (+10M, -1k)','-mtime':'Modified N days ago','-newer':'Newer than a reference file','-exec':'Execute command on each result','-delete':'Delete found files','-maxdepth':'Maximum directory depth to search','-mindepth':'Minimum directory depth','-user':'Files owned by user','-perm':'Files with specific permissions','-not':'Negate condition','-o':'OR condition operator','2>/dev/null':'Suppress permission-denied errors' }},
  tar:  { desc:'Archive and compress files', flags:{ '-c':'Create a new archive','-x':'Extract from archive','-z':'Use gzip compression (.tar.gz)','-j':'Use bzip2 compression (.tar.bz2)','-J':'Use xz compression (.tar.xz)','-v':'Verbose — list files processed','-f':'Specify archive filename','-t':'List archive contents','-C':'Extract to specified directory','--exclude':'Exclude matching files','-p':'Preserve file permissions','-czvf':'Create+gzip+verbose+file','-xzvf':'Extract+gzip+verbose+from file' }},
  chmod:{ desc:'Change file permissions', flags:{ '-R':'Apply recursively','-v':'Verbose — show each change','755':'rwxr-xr-x owner full, others read+exec','644':'rw-r--r-- owner rw, others read','777':'Full permissions for everyone','600':'rw------- owner only','400':'r-------- read-only','+x':'Add execute permission','+r':'Add read permission','+w':'Add write permission','u+x':'Add execute for owner (user)','g+x':'Add execute for group','o-r':'Remove read from others','a+x':'Add execute for all users' }},
  chown:{ desc:'Change file owner and group', flags:{ '-R':'Apply recursively','-v':'Verbose — print each file changed','--reference':'Use ownership of reference file' }},
  curl: { desc:'Transfer data with URLs (HTTP, FTP, etc.)', flags:{ '-X':'HTTP method (GET, POST, PUT, DELETE)','-H':'Add a request header','-d':'Send request body data','-o':'Write output to file','-O':'Save with remote filename','-L':'Follow HTTP redirects','-s':'Silent mode','-v':'Verbose request/response headers','-u':'Basic auth (user:pass)','-k':'Allow insecure certificates','-F':'Upload file via multipart form','-I':'Fetch headers only (HEAD)','-b':'Send cookies','-c':'Write cookies to file','-A':'Set User-Agent string','--max-time':'Request timeout in seconds','--retry':'Retry N times on failure','--compressed':'Request compressed response','-w':'Output format string after transfer' }},
  wget: { desc:'Download files from the web', flags:{ '-O':'Save to specified filename','-q':'Quiet mode','-r':'Download recursively','-P':'Save to directory prefix','--no-check-certificate':'Skip SSL verification','-c':'Continue partial download','--limit-rate':'Cap download speed','-i':'Download URLs from a file' }},
  ssh:  { desc:'Secure remote shell connection', flags:{ '-i':'Identity (private key) file','-p':'Remote port number','-L':'Local port forwarding','-R':'Remote port forwarding','-D':'SOCKS proxy port','-N':'No remote command (tunnels only)','-v':'Verbose debug output','-X':'Enable X11 forwarding','-A':'Forward SSH agent','-o':'Set SSH option','-J':'Jump host proxy','-t':'Force pseudo-TTY allocation' }},
  scp:  { desc:'Secure file copy over SSH', flags:{ '-r':'Copy directories recursively','-i':'Identity (private key) file','-P':'Remote port','-v':'Verbose debug output','-C':'Enable compression' }},
  rsync:{ desc:'Sync files efficiently between locations', flags:{ '-a':'Archive mode (preserves perms/times)','-v':'Verbose','-z':'Compress during transfer','-r':'Recursive','-n':'Dry run — show changes only','--delete':'Delete files not in source','--exclude':'Exclude matching pattern','--include':'Include matching pattern','-e':'Remote shell to use (ssh)','-h':'Human-readable sizes','--progress':'Show transfer progress','-u':'Skip newer destination files' }},
  ps:   { desc:'Show running processes', flags:{ 'aux':'All processes, all users (BSD style)','-e':'All processes','-f':'Full format listing','-u':'Processes for specific user','-p':'Process with PID','-o':'Custom output format','--sort':'Sort by column (--sort=-%cpu)' }},
  kill: { desc:'Send signal to a process by PID', flags:{ '-9':'SIGKILL — force terminate immediately','-15':'SIGTERM — graceful termination (default)','-1':'SIGHUP — reload config','-2':'SIGINT — interrupt (Ctrl+C)','-l':'List signal names','-KILL':'Force kill','-TERM':'Graceful terminate','-HUP':'Hangup/reload' }},
  df:   { desc:'Show disk space usage of filesystems', flags:{ '-h':'Human-readable sizes','-T':'Show filesystem type','-i':'Show inode usage','--total':'Grand total at end','-a':'Include pseudo filesystems' }},
  du:   { desc:'Estimate disk usage of files/directories', flags:{ '-h':'Human-readable sizes','-s':'Summary total only','-a':'Show all files not just dirs','-d':'Limit directory depth','-c':'Show grand total','--exclude':'Exclude matching files','--max-depth':'Maximum depth' }},
  cat:  { desc:'Concatenate and display file contents', flags:{ '-n':'Number all lines','-b':'Number non-empty lines','-A':'Show hidden chars','-s':'Suppress repeated blank lines' }},
  head: { desc:'Output first lines of a file', flags:{ '-n':'Number of lines (default 10)','-c':'Number of bytes' }},
  tail: { desc:'Output last lines of a file', flags:{ '-n':'Number of lines (default 10)','-f':'Follow file for new lines live','-F':'Follow by name (handles rotation)','-c':'Number of bytes','--retry':'Retry if file not accessible' }},
  sed:  { desc:'Stream editor for transforming text', flags:{ '-i':'Edit file in place','-n':'Suppress automatic print','-e':'Add script command','-E':'Extended regular expressions','-r':'Extended regex (GNU alias)' }},
  awk:  { desc:'Pattern scanning and text processing', flags:{ '-F':'Field separator (e.g. -F:)','-v':'Set a variable','-f':'Read program from file' }},
  sort: { desc:'Sort lines of text', flags:{ '-n':'Numeric sort','-r':'Reverse order','-k':'Sort by key/column','-t':'Field delimiter','-u':'Unique lines only','-h':'Human-numeric sort','-f':'Case-insensitive sort' }},
  uniq: { desc:'Filter repeated adjacent lines', flags:{ '-c':'Count occurrences','-d':'Show duplicate lines only','-u':'Show unique lines only','-i':'Case-insensitive' }},
  wc:   { desc:'Count lines, words, and bytes', flags:{ '-l':'Count lines only','-w':'Count words only','-c':'Count bytes only','-m':'Count characters' }},
  echo: { desc:'Print text to standard output', flags:{ '-n':'No trailing newline','-e':'Enable backslash escapes','-E':'Disable backslash escapes' }},
  mkdir:{ desc:'Create directories', flags:{ '-p':'Create parents as needed, no error if exists','-v':'Verbose','-m':'Set permissions mode' }},
  rm:   { desc:'Remove files or directories', flags:{ '-r':'Remove directories recursively','-f':'Force — no prompt, ignore errors','-i':'Prompt before each removal','-v':'Verbose','-rf':'Force recursive delete (CAUTION)' }},
  mv:   { desc:'Move or rename files', flags:{ '-v':'Verbose','-i':'Prompt before overwrite','-n':'No overwrite','-f':'Force overwrite','-b':'Backup existing files' }},
  cp:   { desc:'Copy files and directories', flags:{ '-r':'Copy recursively','-v':'Verbose','-i':'Prompt before overwrite','-n':'No overwrite','-p':'Preserve permissions/timestamps','-a':'Archive mode' }},
  ln:   { desc:'Create hard or symbolic links', flags:{ '-s':'Symbolic (soft) link','-f':'Remove existing destination','-v':'Verbose','-n':'Treat dest as file' }},
  touch:{ desc:'Create file or update timestamps', flags:{ '-a':'Change only access time','-m':'Change only modification time','-t':'Set specific timestamp' }},
  which:{ desc:'Show full path of a command', flags:{}},
  env:  { desc:'Display or set environment variables', flags:{ '-i':'Start with empty environment','-u':'Unset a variable' }},
  export:{ desc:'Set environment variable for child processes', flags:{ '-n':'Remove export mark','-p':'List exported variables' }},
  history:{ desc:'Show command history', flags:{ '-c':'Clear history','-d':'Delete entry at offset','-a':'Append to history file','-r':'Read from history file' }},
  man:  { desc:'Display manual page for a command', flags:{ '-k':'Search manual page names and descriptions','-f':'Display short descriptions' }},
  sudo: { desc:'Execute command as superuser or another user', flags:{ '-u':'Run as specified user','-i':'Simulate initial login','-s':'Run a shell','-l':'List allowed commands','-k':'Invalidate cached credentials','-b':'Run in background','-E':'Preserve environment' }},
  su:   { desc:'Switch to another user account', flags:{ '-':'Login shell (load full environment)','-c':'Execute command as user','-s':'Use specified shell' }},
  ping: { desc:'Test network connectivity to a host', flags:{ '-c':'Send N packets then stop','-i':'Interval between packets','-t':'TTL value','-s':'Packet size','-W':'Timeout per packet','-q':'Quiet — summary only' }},
  netstat:{ desc:'Show network connections and statistics', flags:{ '-t':'TCP connections','-u':'UDP connections','-l':'Listening sockets only','-n':'Show numeric addresses','-p':'Show PID and program name','-a':'All connections','-r':'Routing table','-s':'Statistics by protocol' }},
  ss:   { desc:'Show socket statistics (netstat replacement)', flags:{ '-t':'TCP sockets','-u':'UDP sockets','-l':'Listening only','-n':'Numeric addresses','-p':'Show process info','-a':'All sockets','-e':'Extended info','-i':'TCP internal info' }},
  ip:   { desc:'Manage network interfaces, routing, and tunnels', sub:{ 'addr':'Show/manage IP addresses','link':'Show/manage network interfaces','route':'Show/manage routing table','neigh':'ARP/neighbor table','tunnel':'Manage IP tunnels','rule':'Policy routing rules' }, flags:{ '-4':'IPv4 only','-6':'IPv6 only','-br':'Brief output','-s':'Show statistics','-c':'Colorize output','-j':'JSON output','add':'Add address or route','del':'Delete address or route','show':'Display info','flush':'Remove all entries' }},
  nmap: { desc:'Network port scanner and host discovery', flags:{ '-sV':'Detect service versions','-sC':'Run default scripts','-O':'OS detection','-p':'Specify ports to scan','-A':'Aggressive scan (OS+versions+scripts)','-T4':'Fast timing template','-Pn':'Skip host discovery (assume up)','-sn':'Ping scan only (no ports)','-oN':'Output to normal text file','-oX':'Output to XML file','--open':'Show only open ports','--script':'Run specific NSE script' }},
  systemctl:{ desc:'Control systemd services and units', sub:{ start:'Start a service',stop:'Stop a service',restart:'Stop then start a service',reload:'Reload config without restart',status:'Show service status',enable:'Enable service at boot',disable:'Disable service at boot','is-active':'Check if service is running','is-enabled':'Check if service starts at boot','list-units':'List loaded units','daemon-reload':'Reload systemd config',mask:'Prevent service from starting',unmask:'Re-enable a masked service',cat:'Show unit file contents',edit:'Edit a unit file' }, flags:{ '--now':'Immediately start/stop after enable/disable','--user':'User service manager','-l':'No truncation','--no-pager':'No pager','--all':'Include inactive','--failed':'Failed units only','-q':'Quiet' }},
  journalctl:{ desc:'Query systemd journal logs', flags:{ '-u':'Logs for specific unit','-f':'Follow live','-n':'Last N lines','-e':'Jump to end','--since':'Entries since date/time','--until':'Entries until date/time','-p':'Priority (err, warning, info)','-r':'Reverse order','-o':'Output format (json, cat)','-b':'Current boot entries','-k':'Kernel messages only','--no-pager':'No pager' }},
  crontab:{ desc:'Schedule recurring commands with cron', flags:{ '-e':'Edit crontab','-l':'List crontab entries','-r':'Remove crontab','-u':'Operate on another user crontab' }},
  apt:  { desc:'Debian/Ubuntu package manager', sub:{ install:'Install packages',remove:'Remove packages',update:'Update package index','upgrade':'Upgrade all installed packages','dist-upgrade':'Upgrade with dependency resolution','autoremove':'Remove unused packages',search:'Search for packages',show:'Show package details','list':'List packages',purge:'Remove package and config files','fix-broken':'Fix broken dependencies' }, flags:{ '-y':'Automatic yes to prompts','--no-install-recommends':'Skip recommended packages','-q':'Quiet output','--dry-run':'Simulate without making changes' }},
  yum:  { desc:'RPM-based package manager (RHEL/CentOS)', sub:{ install:'Install packages',remove:'Remove packages',update:'Update packages',search:'Search packages',info:'Show package info',list:'List packages','groupinstall':'Install a package group' }, flags:{ '-y':'Automatic yes','--enablerepo':'Enable a repository','-q':'Quiet' }},
  dnf:  { desc:'Fedora/RHEL 8+ package manager (yum successor)', sub:{ install:'Install packages',remove:'Remove packages',update:'Update packages',search:'Search packages',info:'Show package info',upgrade:'Upgrade packages' }, flags:{ '-y':'Automatic yes','--enablerepo':'Enable repository','-q':'Quiet' }},
  snap: { desc:'Install and manage snap packages', sub:{ install:'Install a snap package',remove:'Remove a snap',refresh:'Update snaps',list:'List installed snaps',info:'Show snap info',find:'Search for snaps' }, flags:{ '--classic':'Install with classic confinement','-y':'Automatic yes' }},

  /* ── DOCKER ────────────────────────────────────────────────────── */
  docker:{ desc:'Container runtime management tool', sub:{ run:'Create and start a new container',build:'Build image from Dockerfile',pull:'Download image from registry',push:'Upload image to registry',ps:'List containers',images:'List local images',stop:'Stop running container',start:'Start stopped container',rm:'Remove container',rmi:'Remove image',exec:'Run command in container',logs:'Fetch container logs',inspect:'Show detailed container info',network:'Manage Docker networks',volume:'Manage Docker volumes',tag:'Tag image with new name',login:'Log in to registry',logout:'Log out from registry',compose:'Multi-container app management',system:'System management',info:'Show system info',version:'Show Docker version',stats:'Live resource usage',cp:'Copy files host↔container' }, flags:{ '-d':'Detached — run in background','-it':'Interactive with pseudo-TTY','-p':'Port mapping (host:container)','-v':'Volume mount (host:container)','--rm':'Auto-remove on exit','--name':'Container name','-e':'Set environment variable','--env-file':'Env vars from file','--network':'Connect to network','--restart':'Restart policy','-a':'Include stopped containers','-q':'IDs only','--no-cache':'Build without cache','-f':'Filter or Dockerfile path','--follow':'Follow log output','--tail':'Lines from end to show','--since':'Logs since timestamp','--platform':'Target platform','--build-arg':'Build-time variable','--target':'Multi-stage build target','-u':'Run as user','-w':'Working directory','--entrypoint':'Override entrypoint','--privileged':'Extended host privileges' }},

  /* ── GIT ───────────────────────────────────────────────────────── */
  git:  { desc:'Distributed version control system', sub:{ clone:'Clone repository from URL',init:'Initialize new Git repo',add:'Stage changes for commit',commit:'Save staged changes to history',push:'Upload commits to remote',pull:'Download and merge remote changes',fetch:'Download without merging',merge:'Merge branch into current',rebase:'Reapply commits onto new base',checkout:'Switch branch or restore file',switch:'Switch to another branch',branch:'List, create, or delete branches',status:'Show working tree status',log:'Show commit history',diff:'Show changes',reset:'Undo commits or unstage',revert:'Create commit that undoes changes',stash:'Temporarily save uncommitted work',tag:'Create or list tags',remote:'Manage remote connections',config:'Get or set configuration',show:'Show commit or file content','cherry-pick':'Apply specific commit',blame:'Show who changed each line',bisect:'Binary search for bug commit',submodule:'Manage sub-repositories' }, flags:{ '-m':'Commit message','-a':'Stage all tracked modified files','-b':'Create and switch to new branch','--all':'All branches or all files','--force':'Override safety checks','-f':'Force operation','--hard':'Reset and discard changes','--soft':'Reset keep changes staged','--oneline':'One commit per line','--graph':'Branch graph in log','--decorate':'Show branch names','-p':'Patch diff per commit','-n':'Limit commits shown','--stat':'File statistics per commit','--cached':'Staged changes only','-d':'Delete branch','-D':'Force delete branch','--squash':'Squash all commits','--no-ff':'Always create merge commit','--rebase':'Rebase instead of merge','--depth':'Shallow clone N commits','--amend':'Modify the last commit','-i':'Interactive rebase','--global':'Config for all repos','--local':'Config for current repo','-u':'Set upstream tracking branch','--tags':'Include all tags','--prune':'Remove stale remote refs','--continue':'Continue in-progress op','--abort':'Abort in-progress op' }},

  /* ── NODE / NPM ─────────────────────────────────────────────────── */
  node: { desc:'Run JavaScript with Node.js runtime', flags:{ '-e':'Evaluate JS expression','-p':'Evaluate and print result','--version':'Show Node.js version','--inspect':'Enable debugger','--inspect-brk':'Break on start for debugger' }},
  npm:  { desc:'Node package manager', sub:{ install:'Install packages',i:'Alias for install',uninstall:'Remove package',update:'Update to latest compatible','run':'Run script from package.json',start:'Run start script',test:'Run test script',init:'Create package.json',publish:'Publish to npm registry',ci:'Clean install from lock file',list:'List installed packages',outdated:'Check for outdated packages',audit:'Check for vulnerabilities' }, flags:{ '--save-dev':'Save to devDependencies','-D':'Alias for --save-dev','--global':'Install globally','-g':'Alias for --global','--production':'Skip devDependencies','--legacy-peer-deps':'Ignore peer dep conflicts','--force':'Force action','-y':'Accept all defaults','--silent':'Suppress output','--dry-run':'Simulate without action','--prefix':'Install location','--registry':'Custom registry URL','--workspaces':'Apply to all workspaces','-w':'Apply to specific workspace' }},
  npx:  { desc:'Execute npm package binaries without installing', flags:{ '-y':'Skip confirmation','--no-install':'Do not install if not found','--package':'Package to install and run','--ignore-existing':'Always use npx-installed version' }},
  pnpm: { desc:'Fast, disk-efficient package manager', sub:{ install:'Install packages',add:'Add a package',remove:'Remove a package',update:'Update packages',run:'Run script','list':'List packages',store:'Manage pnpm store' }, flags:{ '-D':'Save to devDependencies','-g':'Install globally','--frozen-lockfile':'Fail if lockfile not up to date','--filter':'Apply to specific workspace' }},

  /* ── PYTHON / PIP ──────────────────────────────────────────────── */
  python: { desc:'Run Python scripts or REPL', flags:{ '-c':'Execute Python statement','-m':'Run library module as script','-u':'Unbuffered output','-v':'Verbose import tracing','-i':'Inspect after running','--version':'Show Python version' }},
  python3:{ desc:'Run Python 3 scripts or REPL', flags:{ '-c':'Execute Python statement','-m':'Run module as script','-u':'Unbuffered output','--version':'Show Python 3 version' }},
  pip:  { desc:'Python package installer', sub:{ install:'Install packages',uninstall:'Remove package',freeze:'List installed packages with versions',list:'List installed packages',show:'Show package details',download:'Download without installing',check:'Check for compatibility issues' }, flags:{ '-r':'Install from requirements file','--upgrade':'Upgrade to latest version','-U':'Alias for --upgrade','--user':'Install to user directory','--no-deps':'Skip dependencies','--index-url':'Custom index URL','-i':'Alias for --index-url','--quiet':'Suppress output','-q':'Alias for --quiet','--force-reinstall':'Reinstall even if current','--no-cache-dir':'Bypass download cache','--pre':'Include pre-release versions' }},
  pip3: { desc:'Python 3 package installer', sub:{ install:'Install packages',uninstall:'Remove package',freeze:'List installed packages',list:'List packages',show:'Show package details' }, flags:{ '-r':'Install from requirements file','--upgrade':'Upgrade to latest','-U':'Alias for --upgrade','--user':'Install to user dir','--no-deps':'Skip dependencies','-q':'Quiet' }},

  /* ── AWS CLI ───────────────────────────────────────────────────── */
  aws: { desc:'AWS Command Line Interface', sub:{ s3:'Simple Storage Service',s3api:'S3 low-level API',ec2:'Elastic Compute Cloud',ecs:'Elastic Container Service',eks:'Elastic Kubernetes Service',ecr:'Elastic Container Registry',iam:'Identity and Access Management',lambda:'Serverless functions',cloudformation:'Infrastructure-as-code stacks',cloudwatch:'Monitoring and metrics',logs:'CloudWatch Logs',rds:'Relational Database Service',dynamodb:'NoSQL database',elasticache:'In-memory cache',route53:'DNS management',sns:'Push notifications',sqs:'Message queues',secretsmanager:'Secret storage',ssm:'Systems Manager',sts:'Security Token Service',configure:'Set up CLI credentials',autoscaling:'Auto Scaling groups',elbv2:'Application/Network Load Balancer',codebuild:'CI builds',codepipeline:'CI/CD pipelines' }, flags:{ '--region':'AWS region (us-east-1)',  '--profile':'Credentials profile name','--output':'Output: json | text | table | yaml','--query':'JMESPath filter for output','--filters':'Filter by attribute values','--no-cli-pager':'Disable paging','--dry-run':'Validate without executing','--endpoint-url':'Override service endpoint','--recursive':'Recursive S3 operation','--acl':'S3 ACL (public-read, private)','--delete':'Delete extra destination files','--exclude':'Exclude pattern (S3 sync)','--include':'Include pattern (S3 sync)','--role-name':'IAM role name','--policy-arn':'IAM policy ARN','--function-name':'Lambda function name','--stack-name':'CloudFormation stack name','--template-file':'CloudFormation template path','--capabilities':'Required IAM capabilities','--log-group-name':'CloudWatch log group','--cluster':'ECS/EKS cluster name','--service':'ECS service name','--instance-ids':'EC2 instance IDs','--instance-type':'EC2 instance type','--max-items':'Max results to return' }},

  /* ── AZURE CLI ─────────────────────────────────────────────────── */
  az: { desc:'Azure Command Line Interface', sub:{ vm:'Virtual Machine operations',storage:'Storage account operations',acr:'Container Registry',aks:'Kubernetes Service',webapp:'App Service web apps',functionapp:'Function App operations',group:'Resource group management',network:'Networking operations',keyvault:'Key Vault secrets',ad:'Azure Active Directory',role:'RBAC role assignments',cosmosdb:'Cosmos DB',sql:'SQL Database',mysql:'MySQL Database',postgres:'PostgreSQL Database',monitor:'Monitoring and alerts',cdn:'Content Delivery Network',dns:'DNS zones',container:'Container Instances',login:'Log in to Azure',logout:'Log out of Azure',account:'Manage subscriptions',configure:'Set CLI defaults',policy:'Azure Policy',deployment:'ARM/Bicep deployments',bicep:'Bicep template operations' }, flags:{ '--name':'Resource name','--resource-group':'Azure resource group',  '--location':'Azure region (eastus, westeurope)','--subscription':'Subscription ID or name','--image':'Image (UbuntuLTS, Win2019Datacenter)','--size':'VM size (Standard_DS2_v2)','--admin-username':'Admin username','--generate-ssh-keys':'Generate SSH key pair','--output':'Output: json | table | tsv | none','--query':'JMESPath filter','--file':'File path input','--template-file':'ARM/Bicep template file','--parameters':'Template parameters','--container':'Storage container name','--account-name':'Storage account name','--registry':'Container registry name','--cluster-name':'AKS cluster name','--node-count':'Number of nodes','--tier':'Service tier','--sku':'Pricing SKU','--tags':'Resource tags key=value','--yes':'Skip confirmation','-y':'Alias for --yes','--no-wait':'Do not wait for completion','--only-show-errors':'Suppress warnings' }},

  /* ── GOOGLE CLOUD ──────────────────────────────────────────────── */
  gcloud: { desc:'Google Cloud CLI', sub:{ compute:'Compute Engine VMs and networking',container:'Google Kubernetes Engine',app:'App Engine deployment',functions:'Cloud Functions',run:'Cloud Run containers',sql:'Cloud SQL databases',firestore:'Firestore database',storage:'Cloud Storage',pubsub:'Pub/Sub messaging',logging:'Cloud Logging',monitoring:'Cloud Monitoring',builds:'Cloud Build CI',artifacts:'Artifact Registry',secrets:'Secret Manager',iam:'IAM policies',projects:'GCP project management',dns:'Cloud DNS',scheduler:'Cloud Scheduler cron',tasks:'Cloud Tasks queues',kms:'Key Management Service',auth:'Authentication and credentials',config:'Configuration properties',components:'CLI component management',init:'Initialize gcloud config',beta:'Beta commands',alpha:'Alpha commands' }, flags:{ '--project':'GCP project ID','--zone':'GCP zone (us-central1-a)','--region':'GCP region (us-central1)','--account':'GCP account email','--format':'Output: json | yaml | table | text','--filter':'Server-side filter','--limit':'Max resources to list','--quiet':'Suppress prompts','-q':'Alias for --quiet','--machine-type':'Compute Engine type (e2-medium)','--image':'Boot disk image','--image-family':'Image family (debian-11)','--preemptible':'Preemptible (spot) VM','--num-nodes':'Number of GKE nodes','--cluster':'GKE cluster name','--min-nodes':'Min nodes for autoscaling','--max-nodes':'Max nodes for autoscaling','--platform':'Cloud Run platform','--allow-unauthenticated':'Public Cloud Run access','--memory':'Memory limit','--timeout':'Request timeout','--runtime':'Function runtime (python311)','--entry-point':'Cloud Function entry point','--source':'Source code directory','--member':'IAM member (user:, serviceAccount:)','--role':'IAM role (roles/storage.admin)','--enable-autoscaling':'Enable GKE autoscaling' }},
  gsutil:{ desc:'Google Cloud Storage CLI tool', sub:{ cp:'Copy files to/from buckets',mv:'Move files',rm:'Remove objects',ls:'List buckets or objects',mb:'Create a bucket',rb:'Delete an empty bucket',rsync:'Sync directory with bucket',cat:'Print object contents',stat:'Show object metadata',du:'Show bucket/object sizes',iam:'Set IAM policy',acl:'Manage access control lists' }, flags:{ '-r':'Recursive','-m':'Parallel multi-threading','-q':'Quiet mode','-n':'No-clobber','-u':'Skip existing','-p':'Preserve ACLs','-d':'Delete extra files (rsync)','-x':'Exclude by regex','-j':'Compress on-the-fly','-c':'Continue on errors' }},

  /* ── TERRAFORM ─────────────────────────────────────────────────── */
  terraform:{ desc:'HashiCorp infrastructure-as-code tool', sub:{ init:'Initialize providers and backend',plan:'Preview infrastructure changes',apply:'Apply changes to infrastructure',destroy:'Destroy all managed infrastructure',validate:'Check configuration syntax',fmt:'Format .tf files to canonical style',show:'Show state or saved plan',state:'Manage Terraform state file',import:'Import existing resource into state',output:'Show output variable values',workspace:'Manage Terraform workspaces',providers:'Show required providers',refresh:'Sync state with real resources',console:'Interactive expression console',version:'Show Terraform version',login:'Log in to Terraform Cloud',taint:'Mark resource for recreation',force_unlock:'Release stuck state lock' }, flags:{ '-var-file':'Load variables from .tfvars file','-var':'Set variable on command line','-out':'Save plan to file','-auto-approve':'Skip approval prompt','-parallelism':'Concurrent resource operations','-target':'Apply to specific resource only','-destroy':'Create a destroy plan','-replace':'Force resource recreation','-refresh-only':'Refresh state without changes','-json':'Machine-readable JSON output','-no-color':'Disable color output','-upgrade':'Upgrade providers on init','-reconfigure':'Reconfigure backend','-compact-warnings':'Compact warning format','-input':'Prompt for input (false=disable)','-lock':'Lock state file (true/false)','-backend':'Configure backend on init','-recursive':'Also format subdirectories (fmt)','-diff':'Show formatting diff' }},

  /* ── KUBERNETES ─────────────────────────────────────────────────── */
  kubectl:{ desc:'Kubernetes command-line control tool', sub:{ get:'List one or more resources',describe:'Show detailed resource info',apply:'Apply config from file or stdin',delete:'Delete resources',create:'Create resource from file or stdin',edit:'Edit resource in your editor',patch:'Update specific fields',label:'Add or update labels',annotate:'Add or update annotations',expose:'Expose resource as a Service',scale:'Scale a Deployment or StatefulSet',rollout:'Manage rolling updates',logs:'Fetch logs from a pod',exec:'Execute command in a pod container','port-forward':'Forward local port to pod',top:'Show resource usage (CPU/memory)',auth:'Inspect authorization',config:'Modify kubeconfig',cluster_info:'Show cluster connection info',version:'Show client and server versions',run:'Create and run a pod image',cp:'Copy files to/from pod',wait:'Wait for condition',diff:'Show diff of live vs configured state',kustomize:'Build kustomization target',proxy:'Run a proxy to API server',certificate:'Manage certificates' }, flags:{ '-n':'Namespace to operate in','--namespace':'Namespace (same as -n)','--all-namespaces':'All namespaces','-A':'Alias for --all-namespaces','-f':'Filename, directory, or URL','-l':'Label selector filter','-o':'Output format (json, yaml, wide, name)','--watch':'Watch for changes','-w':'Alias for --watch','--dry-run':'client or server dry run','--context':'Specify kubeconfig context','--kubeconfig':'Path to kubeconfig file','--field-selector':'Filter by field value','--selector':'Label selector','-it':'Interactive with TTY','-i':'Interactive stdin','-t':'TTY allocation','--tail':'Lines from end of log','--since':'Logs since duration (1h, 30m)','-c':'Container name in pod','--all':'All resources of type','-R':'Recursive directory','-p':'Previous container instance','--grace-period':'Seconds before force delete','--force':'Force delete','--cascade':'Delete dependent objects','--replicas':'Number of replicas (scale)','--image':'Container image','--env':'Environment variable','--limits':'CPU and memory limits','--requests':'CPU and memory requests','--port':'Port number','--type':'Service type (ClusterIP, NodePort)','--record':'Record command in rollout history','--revision':'Rollout revision number','--timeout':'Timeout for operation','--overwrite':'Allow overwriting labels','--patch-type':'Patch type (json, merge, strategic)','-v':'Verbosity level (1-9)','--show-labels':'Show labels in output','--sort-by':'Sort by field','--token':'Bearer token for auth' }},

  /* ── HELM ──────────────────────────────────────────────────────── */
  helm: { desc:'Kubernetes package manager', sub:{ install:'Install a Helm chart',upgrade:'Upgrade a release',uninstall:'Remove a release',rollback:'Roll back to a previous release',list:'List Helm releases',status:'Show release status',repo:'Manage chart repositories',search:'Search for charts',fetch:'Download chart',pull:'Download chart to local dir',push:'Push chart to registry',template:'Render chart templates locally',lint:'Check chart for issues',show:'Show chart info',history:'Show release history',test:'Run chart tests',package:'Package chart into tar',dependency:'Manage chart dependencies',plugin:'Manage Helm plugins' }, flags:{ '--namespace':'Kubernetes namespace','-n':'Alias for --namespace','--values':'Override values YAML file','-f':'Alias for --values','--set':'Set individual values','--version':'Chart version','--dry-run':'Simulate without installing','--wait':'Wait for pods to be ready','--timeout':'Time to wait for readiness','--atomic':'Roll back on failure','--create-namespace':'Create namespace if missing','--install':'Install if not already installed','--force':'Force upgrade','--reset-values':'Reset to chart defaults','--reuse-values':'Reuse previous values','--debug':'Enable verbose output','--output':'Output format','-o':'Alias for --output','--all':'Include all releases' }},

  /* ── MAKE ──────────────────────────────────────────────────────── */
  make: { desc:'Build automation tool using Makefiles', flags:{ '-f':'Specify Makefile path','-j':'Number of parallel jobs','-n':'Dry run — print without executing','-B':'Unconditionally rebuild targets','-C':'Change to directory first','-s':'Silent — suppress command echoing','-i':'Ignore errors','-k':'Continue despite errors','-p':'Print all rules and variable values','--dry-run':'Print without executing','--jobs':'Parallel jobs','--keep-going':'Continue on error','-e':'Env vars override Makefile vars' }},

  /* ── JQ ────────────────────────────────────────────────────────── */
  jq:   { desc:'Process and query JSON on the command line', flags:{ '-r':'Raw string output (no quotes)','-c':'Compact output (no pretty-print)','-e':'Non-zero exit if last result is false/null','-s':'Read all input as a single array','-n':'Use null as input (no file)','-R':'Raw string input (not JSON)','-f':'Read filter program from file','-e':'Exit non-zero on false/null','-M':'No color (monochrome)','--arg':'Set string variable for filter','--argjson':'Set JSON variable','--rawfile':'Read file contents as string var','--slurpfile':'Slurp file into JSON array' }},

  /* ── OPENSSL ───────────────────────────────────────────────────── */
  openssl:{ desc:'OpenSSL cryptography toolkit', sub:{ genrsa:'Generate RSA private key',req:'Create CSR or self-signed cert',x509:'Show or sign X.509 certificates',pkcs12:'Create/parse PKCS#12 bundles',s_client:'Test TLS connections',dgst:'Compute message digests',enc:'Encrypt or decrypt data',rand:'Generate random bytes',verify:'Verify certificate chain',rsa:'Process RSA keys',ecparam:'EC parameter operations',ec:'Process EC keys' }, flags:{ '-in':'Input file','-out':'Output file','-key':'Private key file','-cert':'Certificate file','-new':'Generate new CSR','-x509':'Output a self-signed cert','-days':'Validity period in days','-nodes':'No DES encryption on the key','-subj':'Certificate subject (DN)','-sha256':'Use SHA-256 digest','-connect':'Host:port for s_client','-CAfile':'CA bundle for verification','-newkey':'Generate new key (rsa:2048)','-extensions':'Extension section to use','-config':'openssl config file','-passin':'Input password source','-passout':'Output password source' }},

  /* ── BASE64 / OTHER UTILS ──────────────────────────────────────── */
  base64:{ desc:'Encode or decode base64 data', flags:{ '-d':'Decode base64 input','-e':'Encode to base64 (default)','-w':'Line wrap at N characters (0=none)','-i':'Read from file' }},
  xargs: { desc:'Build and execute commands from stdin', flags:{ '-I':'Replace string in command','-n':'Max arguments per command run','-P':'Run N processes in parallel','-0':'Null-delimited input (for find -print0)','-d':'Custom delimiter','-t':'Print command before executing','-r':'Do not run if input is empty','--no-run-if-empty':'Same as -r' }},
  tee:   { desc:'Read stdin and write to stdout and files', flags:{ '-a':'Append to files instead of overwrite','-i':'Ignore interrupt signals' }},
  cut:   { desc:'Extract sections from each line', flags:{ '-d':'Delimiter','-f':'Field numbers to extract','-c':'Character positions to extract','-b':'Byte positions to extract' }},
  tr:    { desc:'Translate or delete characters', flags:{ '-d':'Delete specified characters','-s':'Squeeze repeated characters','-c':'Complement the character set' }},
  diff:  { desc:'Compare files line by line', flags:{ '-u':'Unified diff format','-r':'Recursive directory compare','-i':'Ignore case differences','-w':'Ignore whitespace','-b':'Ignore whitespace changes','-q':'Only report if files differ','--color':'Colorize output' }},
  zip:   { desc:'Create ZIP archives', flags:{ '-r':'Recursive','-v':'Verbose','-q':'Quiet','-9':'Maximum compression','-0':'No compression (store only)','-e':'Encrypt with password','-x':'Exclude files matching pattern','-u':'Update existing archive' }},
  unzip: { desc:'Extract ZIP archives', flags:{ '-d':'Extract to directory','-l':'List contents','-v':'Verbose listing','-o':'Overwrite without prompt','-n':'Never overwrite','-q':'Quiet','-p':'Extract to stdout','-P':'Provide decryption password' }},
  gzip:  { desc:'Compress files using gzip', flags:{ '-d':'Decompress','-k':'Keep original file','-v':'Verbose','-9':'Best compression','-1':'Fastest compression','-r':'Recursive','-l':'List compressed file info' }},
  lsof:  { desc:'List open files and the processes using them', flags:{ '-i':'Network connections (or :port)','-p':'Specific PID','-u':'Specific user','-n':'Numerical addresses','-P':'Numerical ports','+D':'All files in directory','-c':'Command name pattern' }},
  strace:{ desc:'Trace system calls and signals for a process', flags:{ '-p':'Attach to running PID','-e':'Filter specific syscalls','-o':'Write output to file','-f':'Follow forked child processes','-c':'Count and summarize syscalls','-T':'Show time spent in each syscall','-v':'Verbose struct output','-s':'Max string size' }},
  htop:  { desc:'Interactive process viewer (enhanced top)', flags:{ '-d':'Refresh delay in tenths of seconds','-u':'Show only user processes','-p':'Show only listed PIDs','-s':'Sort by column' }},
  watch: { desc:'Run command repeatedly and show output', flags:{ '-n':'Interval in seconds (default 2)','-d':'Highlight differences','-e':'Exit on non-zero return code','-t':'Turn off header','-c':'Interpret ANSI colors','-x':'Pass command to exec not shell' }},

  /* ── COMPOSE ───────────────────────────────────────────────────── */
  'docker-compose':{ desc:'Define and run multi-container Docker apps', sub:{ up:'Create and start containers',down:'Stop and remove containers','ps':'List containers','logs':'Show container logs',build:'Build or rebuild services',pull:'Pull images',push:'Push images',restart:'Restart services',stop:'Stop services',start:'Start stopped services',exec:'Execute command in running container',run:'Run one-off command in service',scale:'Set number of service instances',config:'Validate compose file',rm:'Remove stopped containers',pause:'Pause services',unpause:'Unpause services',kill:'Force stop services',port:'Print public port for service' }, flags:{ '-f':'Specify compose file path','--project-name':'Set project name','-d':'Detached mode','--build':'Build before starting','--force-recreate':'Recreate all containers','--no-deps':'No dependency services','--scale':'Scale specific service','--timeout':'Graceful stop timeout','-V':'Renew anonymous volumes','--remove-orphans':'Remove extra services','--tail':'Lines from end of log','--follow':'Follow log output','-T':'Disable TTY' }},

   /* ── MISC COMMON TOOLS ─────────────────────────────────────────── */
  vim:  { desc:'Powerful terminal text editor', flags:{ '-c':'Execute command after opening','-R':'Read-only mode','-u':'Use specific vimrc','-n':'No swap file','+':'Open at last line','+N':'Open at line N' }},
  nano: { desc:'Simple terminal text editor', flags:{ '-l':'Enable line numbers','-v':'Read-only mode','-w':'Disable word wrap','-c':'Constantly show cursor position','-B':'Backup files','-u':'Undo support' }},
  less: { desc:'View file contents page by page', flags:{ '-N':'Show line numbers','-r':'Enable ANSI color codes','-S':'Chop long lines','-i':'Case-insensitive search','-F':'Exit if content fits one screen','+G':'Start at end of file' }},
  more: { desc:'View file contents one screen at a time', flags:{ '-d':'Show navigation prompt','-c':'Clear screen between pages' }},
  screen:{ desc:'Terminal multiplexer — run persistent sessions', flags:{ '-S':'Name the session','-r':'Reattach to session','-list':'List active sessions','-d':'Detach running session','-x':'Attach to shared session' }},
  tmux: { desc:'Terminal multiplexer with split panes and sessions', sub:{ new:'Create new session','new-session':'Create new session','ls':'List sessions','list-sessions':'List sessions',attach:'Attach to session','attach-session':'Attach to session',kill:'Kill a session','kill-session':'Kill a session','kill-server':'Stop tmux server',split:'Split window',source:'Source config file' }, flags:{ '-s':'Session name','-d':'Detach other clients','-t':'Target session or window','-f':'Config file','-c':'Start directory','-L':'Server socket name' }},

  /* ── JVM / JAVA ────────────────────────────────────────────────── */
  java: { desc:'Run Java application or JVM', flags:{ '-jar':'Run JAR file','-cp':'Classpath','-classpath':'Classpath','-Xmx':'Maximum heap size (-Xmx512m)','-Xms':'Initial heap size','-D':'Set system property','-version':'Show Java version','--version':'Show Java version','-ea':'Enable assertions','-server':'Server JVM mode','-verbose':'Verbose output' }},
  mvn:  { desc:'Apache Maven build tool', sub:{ clean:'Remove build artifacts',compile:'Compile source code',test:'Run unit tests',package:'Package into JAR/WAR',install:'Install to local Maven repo',deploy:'Deploy to remote Maven repo',validate:'Validate project structure','spring-boot:run':'Run Spring Boot app','dependency:tree':'Show dependency tree' }, flags:{ '-D':'Set system property / property','-P':'Activate profile','-f':'Use specific pom.xml','-s':'Use specific settings.xml','-pl':'Build specific modules','-am':'Also build dependencies','-U':'Force update snapshots','-T':'Parallel build threads','-q':'Quiet output','-X':'Debug output','--no-transfer-progress':'Suppress download progress','-DskipTests':'Skip running tests','-e':'Show error stack traces' }},
  gradle:{ desc:'Gradle build automation tool', sub:{ build:'Build the project',clean:'Delete build directory',test:'Run tests',assemble:'Assemble outputs',check:'Run all verifications',run:'Run the application',dependencies:'Show dependency tree',tasks:'List available tasks',properties:'Show project properties' }, flags:{ '--no-daemon':'Do not use Gradle daemon','--daemon':'Use Gradle daemon','-p':'Project directory','--project-dir':'Project directory','-b':'Build file path','--build-file':'Build file path','--info':'Info logging','-i':'Alias for --info','--debug':'Debug logging','-d':'Alias for --debug','-q':'Quiet mode','--quiet':'Quiet mode','--parallel':'Parallel project building','--continue':'Continue despite failures','-x':'Exclude task','-t':'Continuous build','--offline':'Use cached deps only','-Pprop':'Set project property','--rerun-tasks':'Force all tasks to rerun','--scan':'Generate Gradle build scan' }},
};

/* ── Helper: look up a flag in a command's flags ─────────────────── */
function lookupFlag(cmdEntry, flag) {
  if (!cmdEntry || !cmdEntry.flags) return null;
  // exact match
  if (cmdEntry.flags[flag]) return cmdEntry.flags[flag];
  // strip = value: --output=json → --output
  const bare = flag.replace(/=.*$/, '');
  if (cmdEntry.flags[bare]) return cmdEntry.flags[bare];
  // combined short flags: -lah → check each letter
  if (/^-[a-zA-Z]{2,}$/.test(flag)) {
    const combined = flag.slice(1).split('').map(c => `-${c}`);
    const found = combined.map(c => cmdEntry.flags[c]).filter(Boolean);
    if (found.length) return found.join(' + ');
  }
  return null;
}

/* ── Helper: get subcommand description ─────────────────────────── */
function lookupSub(cmdEntry, token) {
  if (!cmdEntry || !cmdEntry.sub) return null;
  return cmdEntry.sub[token] || null;
}
